### ISSUE TITLE
why not use node-k8s-client

### ISSUE THREAD

**Issue by veeramarni** [hyperhq/hyper-connector-k8s#2]
I was wondering why you not using `node-k8s-client` instead of `@kubernetes/typescript-node`

**Comment by imeoer** [comment]
@veeramarni Use `@kubernetes/typescript-node` to more easily integrate into the typescript project, such as intelligent code completion, easier k8s type declaration such as node, pod, container data structures and so on.

**Comment by veeramarni** [comment]
I now, but was it a stable package, I know it's now in wip. Whereas node-k8s-client also provides you the intelliSense as it is written in typescript.

**Comment by imeoer** [comment]
@veeramarni It seems no type declaration of k8s data structure, but yes, it's a stable package. Actually, `@kubernetes/typescript-node` is from the aci-connector-k8s project. :)

**Comment by veeramarni** [comment]
So this is the one https://github.com/kubernetes-client/typescript you are referring.
